---

neat_config_file: config/config-ctrnn0

server_config_file: /home/hiryugan/Documents/torcs-server/config/example_torcs_config_test0.xml

save_path: neat_results/exp0/

port: 9

fitness_function_file: fitness_functions/fit1.py


tracks:
  - name: wheel-2
    category: road

  - name: alpine-1
    category: road

  - name: michigan
    category: oval

output_model:
  - feature: accel
    name: None
    used: False

  - feature: brake
    name: None
    used: False

  - feature: steer
    name: pre_train/models/mod_temporal_torch_3
    used: True

merge_accel_brake: sum3333

avoid_go_out: False
