---

neat_config_file: config/config-ctrnn

server_config_file: /home/hiryugan/Documents/torcs-server/example_torcs_config.xml

save_path: neat_results/exp1/

port: 1

fitness_function_file: fitness_functions/fit1.py


tracks:
  - name: forza
    category: road

  - name: alpine-1
    category: road

  - name: michigan
    category: oval

output_model:
  - feature: Acceleration
    name: None
    used: False

  - feature: Brake
    name: None
    used: False

  - feature: Steering
    name: pre_train/models/test_steering
    used: False
