---

neat_config_file: config/config-ctrnn9

server_config_file: /home/hiryugan/Documents/torcs-server/config/example_torcs_config_test9.xml

save_path: neat_results/exp9/

port: 8

fitness_function_file: fitness_functions/fit1.py


tracks:
  - name: alpine-1
    category: road

  - name: alpine-1
    category: road

  - name: michigan
    category: oval

output_model:
  - feature: accel
    name: None
    used: False

  - feature: brake
    name: None
    used: False

  - feature: steer
    name: pre_train/models/mod_temporal_torch_3_nicer
    used: True

merge_accel_brake: False

avoid_go_out: True
