---
neat_config_file: path/to/neat_config

server_config_file: path/to/server_config

fitness_function_file: path/to/fitness_config

save_path: path/to/save_path

port: port_number (from 0 to 9)

tracks:
  - name: forza
    category: road

  - name: alpine-1
    category: road

  - name: michigan
    category: oval

output_model:
  - feature: Acceleration
    name: Filename
    used: True

  - feature: Brake
    name: Filename
    used: False

  - feature: Steering
    name: None
    used: False

